// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShopAnalysis.CouponSaleItemAPI.Data;

#nullable disable

namespace eShopAnalysis.CouponSaleItemAPI.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20231010164228_InitDbPostgres")]
    partial class InitDbPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShopAnalysis.CouponSaleItemAPI.Models.Coupon", b =>
                {
                    b.Property<Guid>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CouponStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEnded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<double>("DiscountValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MinOrderValueToApply")
                        .HasColumnType("double precision");

                    b.Property<int>("RewardPointRequire")
                        .HasColumnType("integer");

                    b.HasKey("CouponId");

                    b.HasAlternateKey("CouponCode");

                    b.HasIndex("CouponCode");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CouponCode"), new[] { "CouponStatus" });

                    b.ToTable("Coupon", "Discount");
                });

            modelBuilder.Entity("eShopAnalysis.CouponSaleItemAPI.Models.SaleItem", b =>
                {
                    b.Property<Guid>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessKey")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEnded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<double>("DiscountValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardPointRequire")
                        .HasColumnType("integer");

                    b.Property<int>("SaleItemStatus")
                        .HasColumnType("integer");

                    b.HasKey("SaleItemId");

                    b.HasIndex("ProductId", "ProductModelId", "BusinessKey");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProductId", "ProductModelId", "BusinessKey"), new[] { "SaleItemStatus" });

                    b.ToTable("SaleItem", "Discount");
                });
#pragma warning restore 612, 618
        }
    }
}
