// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShopAnalysis.CustomerLoyaltyProgramAPI.Data;
using eShopAnalysis.CustomerLoyaltyProgramAPI.Models;

#nullable disable

namespace eShopAnalysis.CustomerLoyaltyProgramAPI.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20240110173254_InitialPostgresDb")]
    partial class InitialPostgresDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShopAnalysis.CustomerLoyaltyProgramAPI.Models.RewardTransaction", b =>
                {
                    b.Property<Guid>("RewardTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTransition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<OriginJson>("Origin")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PointAfterTransaction")
                        .HasColumnType("integer");

                    b.Property<int>("PointBeforeTransaction")
                        .HasColumnType("integer");

                    b.Property<int>("PointTransition")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RewardTransactionId");

                    b.ToTable("RewardTransaction", "CustomerLoyaltyProgram");
                });

            modelBuilder.Entity("eShopAnalysis.CustomerLoyaltyProgramAPI.Models.UserRewardPoint", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RewardPoint")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserRewardPoint", "CustomerLoyaltyProgram");
                });
#pragma warning restore 612, 618
        }
    }
}
